name: fraudebot

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: laravel-clean-app
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/backend
    volumes:
      - ./backend:/var/www/backend
      - ./docker/php/conf.d:/usr/local/etc/php/conf.d
    depends_on:
      - db
      - redis
    networks:
      - fraudebot-network
      - fraudebot-api-network
    env_file:
      - ./docker/php/.env.php

  web:
    image: nginx:alpine
    container_name: laravel_web
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/backend
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - fraudebot-network

  frontend:
    image: node:20-alpine
    container_name: react_frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - 80:80
    command: sh -c "if [ -f package.json ]; then npm install && npm run dev; else tail -f /dev/null; fi"
    networks:
      - fraudebot-network

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    env_file:
      - ./docker/db/.env.db
    ports:
      - 3306:3306
    volumes:
      - fraudebot-db-data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - fraudebot-api-network

  redis:
    image: redis:alpine
    container_name: redis_cache
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - fraudebot-redis-data:/data
    networks:
      - fraudebot-api-network

networks:
  fraudebot-network:
    driver: bridge

  fraudebot-api-network:
    driver: bridge

volumes:
  fraudebot-db-data:
  fraudebot-redis-data:
